#!/bin/bash
# ============================================================
# Agents on Azure - Bicep Deployment Script
# ============================================================
# Deploys infrastructure using Azure Bicep templates.
# Generates .env file from deployment outputs.
#
# Usage:
#   ./deploy.sh [dev|prod]
#
# Prerequisites:
#   - Azure CLI (az) installed and logged in
#   - Bicep CLI installed (az bicep install)
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BICEP_DIR="${SCRIPT_DIR}/../bicep"
PROJECT_ROOT="${SCRIPT_DIR}/../.."

# Default environment
ENV="${1:-dev}"

# Validate environment
if [[ ! "$ENV" =~ ^(dev|staging|prod)$ ]]; then
    echo "Error: Invalid environment '$ENV'. Use: dev, staging, or prod"
    exit 1
fi

# Resource group name
RG="rg-agents-on-azure-${ENV}"
LOCATION="koreacentral"

echo ""
echo "============================================================"
echo "  Agents on Azure - Bicep Deployment"
echo "  Environment: ${ENV}"
echo "  Resource Group: ${RG}"
echo "============================================================"
echo ""

# ============================================================
# 1. Create Resource Group
# ============================================================
echo "==> Creating resource group..."
az group create --name "$RG" --location "$LOCATION" --output none

# ============================================================
# 2. Deploy Bicep Template
# ============================================================
echo "==> Deploying Bicep template..."
DEPLOYMENT_NAME="agents-${ENV}-$(date +%Y%m%d%H%M%S)"

OUTPUTS=$(az deployment group create \
    --name "$DEPLOYMENT_NAME" \
    --resource-group "$RG" \
    --template-file "${BICEP_DIR}/main.bicep" \
    --parameters "${BICEP_DIR}/parameters/${ENV}.bicepparam" \
    --query "properties.outputs" \
    --output json)

echo "==> Deployment completed successfully!"

# ============================================================
# 3. Generate .env file
# ============================================================
echo "==> Generating .env file..."

ENV_FILE="${PROJECT_ROOT}/.env"

# Extract outputs
AZURE_OPENAI_ENDPOINT=$(echo "$OUTPUTS" | jq -r '.AZURE_OPENAI_ENDPOINT.value // empty')
AZURE_OPENAI_MODEL=$(echo "$OUTPUTS" | jq -r '.AZURE_OPENAI_MODEL.value // empty')
AZURE_SERVICEBUS_NAMESPACE=$(echo "$OUTPUTS" | jq -r '.AZURE_SERVICEBUS_NAMESPACE.value // empty')
AZURE_EVENTHUB_NAMESPACE=$(echo "$OUTPUTS" | jq -r '.AZURE_EVENTHUB_NAMESPACE.value // empty')
AZURE_EVENTGRID_ENDPOINT=$(echo "$OUTPUTS" | jq -r '.AZURE_EVENTGRID_ENDPOINT.value // empty')
AZURE_STORAGE_ACCOUNT_NAME=$(echo "$OUTPUTS" | jq -r '.AZURE_STORAGE_ACCOUNT_NAME.value // empty')
APPLICATIONINSIGHTS_CONNECTION_STRING=$(echo "$OUTPUTS" | jq -r '.APPLICATIONINSIGHTS_CONNECTION_STRING.value // empty')

cat > "$ENV_FILE" << EOF
# Auto-generated by deploy.sh on $(date -Iseconds)
# Environment: ${ENV}
# Resource Group: ${RG}

# Azure OpenAI
AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL}

# Azure Service Bus
AZURE_SERVICEBUS_NAMESPACE=${AZURE_SERVICEBUS_NAMESPACE}

# Azure Event Hubs
AZURE_EVENTHUB_NAMESPACE=${AZURE_EVENTHUB_NAMESPACE}
AZURE_EVENTHUB_NAME=analysis-results

# Azure Event Grid
AZURE_EVENTGRID_ENDPOINT=${AZURE_EVENTGRID_ENDPOINT}

# Azure Storage
AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}

# Observability
APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
EOF

echo "==> .env file created at: ${ENV_FILE}"

# ============================================================
# 4. Assign RBAC roles to current user (for local development)
# ============================================================
echo "==> Assigning RBAC roles to current user..."

CURRENT_USER_ID=$(az ad signed-in-user show --query id -o tsv 2>/dev/null || echo "")

if [[ -n "$CURRENT_USER_ID" ]]; then
    echo "    User ID: ${CURRENT_USER_ID}"
    
    # Cognitive Services OpenAI User
    echo "    - Cognitive Services OpenAI User..."
    az role assignment create \
        --assignee "$CURRENT_USER_ID" \
        --role "Cognitive Services OpenAI User" \
        --scope "/subscriptions/$(az account show --query id -o tsv)/resourceGroups/${RG}" \
        --output none 2>/dev/null || true

    # Azure Service Bus Data Owner
    echo "    - Azure Service Bus Data Owner..."
    az role assignment create \
        --assignee "$CURRENT_USER_ID" \
        --role "Azure Service Bus Data Owner" \
        --scope "/subscriptions/$(az account show --query id -o tsv)/resourceGroups/${RG}" \
        --output none 2>/dev/null || true

    # Azure Event Hubs Data Owner
    echo "    - Azure Event Hubs Data Owner..."
    az role assignment create \
        --assignee "$CURRENT_USER_ID" \
        --role "Azure Event Hubs Data Owner" \
        --scope "/subscriptions/$(az account show --query id -o tsv)/resourceGroups/${RG}" \
        --output none 2>/dev/null || true

    # EventGrid Data Sender
    echo "    - EventGrid Data Sender..."
    az role assignment create \
        --assignee "$CURRENT_USER_ID" \
        --role "EventGrid Data Sender" \
        --scope "/subscriptions/$(az account show --query id -o tsv)/resourceGroups/${RG}" \
        --output none 2>/dev/null || true

    # Storage Blob Data Contributor
    echo "    - Storage Blob Data Contributor..."
    az role assignment create \
        --assignee "$CURRENT_USER_ID" \
        --role "Storage Blob Data Contributor" \
        --scope "/subscriptions/$(az account show --query id -o tsv)/resourceGroups/${RG}" \
        --output none 2>/dev/null || true

    # Storage Queue Data Contributor
    echo "    - Storage Queue Data Contributor..."
    az role assignment create \
        --assignee "$CURRENT_USER_ID" \
        --role "Storage Queue Data Contributor" \
        --scope "/subscriptions/$(az account show --query id -o tsv)/resourceGroups/${RG}" \
        --output none 2>/dev/null || true

    echo "==> RBAC roles assigned!"
else
    echo "    Warning: Could not determine current user ID. Skipping RBAC assignments."
    echo "    Run 'az login' and try again, or assign roles manually."
fi

echo ""
echo "============================================================"
echo "  Deployment Complete!"
echo "============================================================"
echo ""
echo "Next steps:"
echo "  1. Review generated .env file"
echo "  2. Wait ~5 minutes for RBAC propagation"
echo "  3. Run: cd ${PROJECT_ROOT} && uv sync && uv run python samples/semantic-kernel/single-agent/src/main.py"
echo ""
